apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "cluster-issuer"
spec:
  acme:
    server: {{ .Values.acmeServer }}
    email: {{ .Values.issuer.email }}
    privateKeySecretRef:
      name: account-key
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingress.className }}
