apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "cluster-issuer"
spec:
  vault:
    path: pki_int/root/sign-intermediate
    server: https://vault-internal.vault.svc.cluster.local:8200
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTmpJNE9URXdOVGd3SGhjTk1qVXhNVEV4TVRrMU56TTRXaGNOTXpVeE1UQTVNVGsxTnpNNApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTmpJNE9URXdOVGd3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRT3lVTTZKOGRKR1NTcXRKMGJJdWZ5eU4rR1pKZGNhRUpFWUJ3SitObXYKSnFOcVlGM280QkR6cFlnNW5uaVVqNjJjRCtnWWFpVmpSZm5PMzNQQ1ExTllvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTZUZk4yaFBXNWtXVXQ5Nms0ckJwCldkRFFrS1l3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU4zMWJ6Z081eE9ybzRuY0piWWJ3YmVGL1BaaWtTbmoKVW0rMkhoZHRuZUZjQWlFQTJ5d0NvaUM3ZXliNWZNU285N2JIOVpDOGl2UUM5eDhrdk5CcVVqODlRSms9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    auth:
      appRole:
        path: approle
        # RoleId taken from vault app role
        roleId: 3e363c24-592a-8ec7-fbe5-2f68f8ed1783
        secretRef:
          name: cert-manager-vault-approle
          key: secretId