apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: backend-trust
  namespace: argocd  # Match your Traefik namespace
spec:
#  rootCAs:
#    secret:
#      name: backend-ca-secret  # Secret with ca.crt
  insecureSkipVerify: true
  serverName: "argo.internal"  # Optional SNI override
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ir-argo
  namespace: argocd
spec:
  routes:
    - kind: Rule
      match: Host(`argo.internal`)
      services:
        - name: argocd-server
          port: 443
          scheme: https
          serversTransport: backend-trust